### ISSUE TITLE
S3 Datasets not accessible

### ISSUE THREAD

**Issue by lastweek** [NetSys/disaggregation#3]
Hi Peter,

I was trying to use the script https://github.com/NetSys/disaggregation/blob/master/download-trace.sh to download the trace from S3, but found none of them is accessible anymore. Did you move the datasets elsewhere? Thank you

**Comment by pxgao** [comment]
Hi, I graduated 2 years ago and the trace is removed since then. I still have them on my local machine so if you want it, you can setup a server and I am happy to upload it to your server. It is about 40G. My email is peterxianggao # gmail.com

**Comment by lastweek** [comment]
Hi Peter, thanks for the reply. I got a copy of the data from a former labmate.
