### ISSUE TITLE
Question regarding disaggregation-trace

### ISSUE THREAD

**Issue by linusyukwong** [NetSys/disaggregation#4]
Hi Peter, I am very interested in the disaggregation trace from this project.
When I run `download-trace.sh`, it gives me an error saying that 404 is not found.
I tried to manually access the website for each s3 objects, but aws s3 returns that "The specified bucket does not exist".
Thank you.

**Comment by pxgao** [comment]
Hi Linus,

       The trace is not available any more as it took too much S3 space.
You can try regenerating it using the script in the depot. You will need to
first config a cluster and then run
https://github.com/NetSys/disaggregation/blob/master/rmem/all_app.sh

Regards
Peter

**Comment by linusyukwong** [comment]
I see. Thank you for your reply!
